services:
  word-db:
    hostname: word-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - tcpByPakkePost
    ports:
      - 1433:1433

volumes:
  mssql-data:
    
networks:
  tcpByPakkePost:
